ALTER TABLE crews ADD COLUMN is_frozen INTEGER NOT NULL DEFAULT 0;
ALTER TABLE crews ADD COLUMN freeze_reason TEXT;
ALTER TABLE crews ADD COLUMN frozen_by TEXT REFERENCES users(id);
ALTER TABLE crews ADD COLUMN frozen_at TEXT;